// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoQKojcpMgzpeRXigs7SgSbXxY70bms1A',
    appId: '1:368020635373:web:a767def17eb26e025196e4',
    messagingSenderId: '368020635373',
    projectId: 'social-platform-16686',
    authDomain: 'social-platform-16686.firebaseapp.com',
    storageBucket: 'social-platform-16686.firebasestorage.app',
    measurementId: 'G-283YTCK9ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoIeZxcDBaki-aQWED9AklKDmWN9HEIes',
    appId: '1:368020635373:android:93a7aa54bfcd0c7b5196e4',
    messagingSenderId: '368020635373',
    projectId: 'social-platform-16686',
    storageBucket: 'social-platform-16686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg1KffEcWLuYoYv5Lpvu2AWBnl42a7FsE',
    appId: '1:368020635373:ios:324f9f57a5ce994e5196e4',
    messagingSenderId: '368020635373',
    projectId: 'social-platform-16686',
    storageBucket: 'social-platform-16686.firebasestorage.app',
    iosBundleId: 'com.example.socialPlatform',
  );
}
